platform :ios, '9.0'

target 'Todolist' do

  use_frameworks!

  # Pods for Todolist

pod 'RealmSwift'
pod 'SwipeCellKit'
pod 'ChameleonFramework/Swift', :git => 'https://github.com/wowansm/Chameleon.git', :branch => 'swift5'
end
